Query counters capabilities with new SAI API
shlomibitton/sonic-sairedis pull request #4
Opened 2021-08-31 10:16 UTC by shlomibitton

Signed-off-by: Shlomi Bitton shlomibi@nvidia.com

Implement new SAI API to query counters capabilities.
This API is used to get the capabilities in a way which is not accessing the HW and performs much quicker.
New API introduced on this PR: opencomputeproject/SAI#1148

2021-08-31 10:49 UTC, stepanblyschak requested changes

2021-08-31 10:49 UTC, stepanblyschak commented on vslib/src/VirtualSwitchSaiInterface.cpp
> +    return SAI_STATUS_NOT_IMPLEMENTED;
How is it going to be VS tested if it is not implemented?

2021-08-31 10:49 UTC, stepanblyschak commented on syncd/FlexCounter.cpp
> +        delete[] stats_capability.list;
Should this be part of the "else if (status == SAI_STATUS_BUFFER_OVERFLOW)" branch?

2021-08-31 10:49 UTC, stepanblyschak commented on syncd/FlexCounter.cpp
> +            if (m_statsMode == SAI_STATS_MODE_READ_AND_CLEAR && !((stats_capability.list)[i].stat_modes & SAI_STATS_MODE_READ_AND_CLEAR))
This condition may be hard to read. May I propose to create a function:
```c++
bool isStatsModeSupported(sai_stat_capability_t, statsMode)
```
?

2021-08-31 10:49 UTC, stepanblyschak commented on syncd/FlexCounter.cpp
> +        stats_capability.list = new sai_stat_capability_t[stats_capability.count];
Try to avoid ```new/delete```, use objects with memory allocation bound to the life time of the object.
Here, an std::vector should be used instead.

2021-08-31 10:49 UTC, stepanblyschak commented on syncd/FlexCounter.cpp
> +    stats_capability.list = NULL;
Use ```nullptr``` (since C++ 11)

2021-08-31 10:49 UTC, stepanblyschak commented on syncd/FlexCounter.cpp
> +        sai_serialize_object_id(priorityGroupRid).c_str());
Here, you might miss to deallocate ```stats_capability.list```. Use vector instead

2021-08-31 10:49 UTC, stepanblyschak commented on syncd/FlexCounter.cpp
> +    if(status == SAI_STATUS_NOT_IMPLEMENTED)
SAI_STATUS_NOT_IMPLEMENTED or SAI_STATUS_NOT_SUPPORTED

2021-08-31 11:46 UTC, shlomibitton commented on syncd/FlexCounter.cpp
> +        delete[] stats_capability.list;
This should cover both cases if the API call failed for some reason.
if getStats or queryStatsCapability will fail, it will be handled here.

2021-08-31 11:47 UTC, shlomibitton commented on syncd/FlexCounter.cpp
> +            if (m_statsMode == SAI_STATS_MODE_READ_AND_CLEAR && !((stats_capability.list)[i].stat_modes & SAI_STATS_MODE_READ_AND_CLEAR))
Yes I agree, will add a function for it

2021-08-31 14:53 UTC, shlomibitton commented on syncd/FlexCounter.cpp
> +        stats_capability.list = new sai_stat_capability_t[stats_capability.count];
Done.

2021-08-31 14:54 UTC, shlomibitton commented on syncd/FlexCounter.cpp
> +    stats_capability.list = NULL;
Done

2021-08-31 14:54 UTC, shlomibitton commented on syncd/FlexCounter.cpp
> +        sai_serialize_object_id(priorityGroupRid).c_str());
Done

2021-08-31 14:56 UTC, shlomibitton commented on syncd/FlexCounter.cpp
> +    if(status == SAI_STATUS_NOT_IMPLEMENTED)
Done

2021-08-31 15:42 UTC, stepanblyschak requested changes

2021-08-31 15:42 UTC, stepanblyschak commented on syncd/FlexCounter.cpp
> +            sai_port_stat_t counter = static_cast<sai_port_stat_t>((stats_capability.list)[i].stat_enum);
Use after free bug.
The memory pointed by ```stats_capability.list``` is **_owned_** by the ```std::vector<sai_stat_capability_t> statCapabilityList(stats_capability.count)```. The destructor for ```std::vector``` has been called on line 1817.

2021-08-31 15:42 UTC, stepanblyschak commented on syncd/FlexCounter.cpp
> +                {
Incorrect indentation.

2021-08-31 15:55 UTC, stepanblyschak commented on syncd/FlexCounter.cpp
> +        delete[] stats_capability.list;
getStats's status is handled here. https://github.com/shlomibitton/sonic-sairedis/blob/455e85c094cab3de2424773d3c5ffa4d5b493a32/syncd/FlexCounter.cpp#L1793 followed by a continue and return at the end of the block, so this condition is not relevant to getStats.

In general I find the resulting function very complicated to read and follow the code due to branching and status handling which happens sometimes right after API call sometimes not. I would suggest to create two functions:

```c++
/* Legacy way of getting a list of supported counters by reading the counter value and imply the counter availability based on SAI status code. */
sai_status_t readGetPortSupportedPortCounters(std::set<sai_port_stat_t>& portStats);

/* Query SAI supported port counters */
sai_status_t querySupportedPortCounters(std::set<sai_port_stat_t>& portStats);
```

And in the code:

```c++
if (!querySupportedPortCounters(m_portCounters))
{
    /* fallback to legacy approach */
    readGetPortSupportedPortCounters(m_portCounters)
}
```

2021-09-01 11:27 UTC, shlomibitton commented on syncd/FlexCounter.cpp
> +            sai_port_stat_t counter = static_cast<sai_port_stat_t>((stats_capability.list)[i].stat_enum);
Fixed

2021-09-02 12:28 UTC, shlomibitton commented on syncd/FlexCounter.cpp
> +        delete[] stats_capability.list;
Done.

2021-09-02 13:06 UTC, stepanblyschak requested changes

2021-09-02 13:06 UTC, stepanblyschak commented on syncd/FlexCounter.cpp
> +            sai_serialize_object_id(portRid).c_str());
indentation issue

2021-09-02 13:06 UTC, stepanblyschak commented on syncd/FlexCounter.cpp
> +                sai_port_stat_t counter = static_cast<sai_port_stat_t>((stats_capability.list)[i].stat_enum);
Why do you need extra parenthesis?
```suggestion
                sai_port_stat_t counter = static_cast<sai_port_stat_t>(stats_capability.list[i].stat_enum);
```

2021-09-02 13:06 UTC, stepanblyschak commented on syncd/FlexCounter.cpp
> +                    {
indentation issue

2021-09-02 13:06 UTC, stepanblyschak commented on syncd/FlexCounter.cpp
> +    uint64_t value;
what is this value used for?

2021-09-02 13:06 UTC, stepanblyschak commented on syncd/FlexCounter.cpp
> +        SAI_OBJECT_TYPE_INGRESS_PRIORITY_GROUP,
indentation issue

2021-09-02 13:06 UTC, stepanblyschak commented on syncd/FlexCounter.cpp
> +            for (uint32_t i = 0; i < stats_capability.count; i++)
Why not to use for range loop since you anyway use a vector?
```suggestion
            for (auto capability: statCapabilityList)
```

2021-09-02 14:14 UTC, shlomibitton commented on syncd/FlexCounter.cpp
> +            sai_serialize_object_id(portRid).c_str());
I don't see an issue, can you specify what is wrong?

2021-09-02 14:16 UTC, shlomibitton commented on syncd/FlexCounter.cpp
> +                sai_port_stat_t counter = static_cast<sai_port_stat_t>((stats_capability.list)[i].stat_enum);
Done

2021-09-02 14:17 UTC, shlomibitton commented on syncd/FlexCounter.cpp
> +                    {
Fixed

2021-09-02 14:18 UTC, shlomibitton commented on syncd/FlexCounter.cpp
> +    uint64_t value;
I am not sure, it was there before on the legacy approach, I moved this entire block to the old approach function

2021-09-02 14:32 UTC, shlomibitton commented on syncd/FlexCounter.cpp
> +            for (uint32_t i = 0; i < stats_capability.count; i++)
Fixed

2021-09-02 14:43 UTC, stepanblyschak commented on syncd/FlexCounter.cpp
> +            sai_serialize_object_id(portRid).c_str());
```c++
SWSS_LOG_INFO("Unable to get port supported counters for %s",
sai_serialize_object_id(portRid).c_str());
```

vs

```c++
SWSS_LOG_INFO("Unable to get port supported counters for %s",
    sai_serialize_object_id(portRid).c_str());
```

2021-09-02 14:58 UTC, shlomibitton commented on syncd/FlexCounter.cpp
> +            sai_serialize_object_id(portRid).c_str());
Got it, fixed

2021-09-02 15:01 UTC, stepanblyschak approved these changes
LGTM except for the VS question. Not sure what is the plan for VS tests to cover this feature

2021-09-09 11:05 UTC, stepanblyschak approved these changes

2021-09-09 11:28 UTC, merged